package service;

import model.User;

import java.io.FileWriter;
import java.util.List;

public class RscExporter {

    public static void export(
            List<User> users,
            String filePath)
            throws Exception {

        FileWriter writer =
                new FileWriter(filePath);

        for (User user : users) {

            writer.write(
                    "/ip hotspot user add " +
                            "name=" + user.getUsername() +
                            " password=" + user.getPassword() +
                            " profile=" + user.getProfile() +
                            " limit-uptime=" + user.getUptime() +
                            " server=" + user.getServer() +
                            " comment=\"Generated by MikroTik Hotspot Manager\"" +
                            "\n"
            );
        }

        writer.close();
    }
}